FROM ezeddin/nvidia-gpu:conda.dev.k8s

USER root

RUN curl -fsSL https://code-server.dev/install.sh | sh

### Create a new user
ARG UNAME=coder 
ARG UID=1000
ARG GID=100
RUN groupadd --gid $GID -o $UNAME && \
    useradd \
      --uid $UID \
      --gid $GID \
      --create-home \
      --shell /bin/bash \ 
      $UNAME && \
    passwd -d $UNAME && \
    adduser $UNAME sudo
RUN echo "$UNAME ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/$UNAME && \
    chmod 0440 /etc/sudoers.d/$UNAME
WORKDIR /home/$UNAME

RUN chown -R $UNAME:$UNAME /opt/conda
RUN cp -r /root/.bashrc /home/$UNAME && \
    cp -r /root/.conda /home/$UNAME && \
    chown -R $UNAME:$UNAME /home/$UNAME

USER $UNAME

COPY --chown=$UNAME:$UNAME code-server-update.sh /opt/scripts/code-server-update.sh
RUN chmod 0777 /opt/scripts/code-server-update.sh

RUN echo '\nexport PATH="/opt/scripts:$PATH"' >> /home/$UNAME/.bashrc

EXPOSE 8300
CMD ["code-server", "--host", "0.0.0.0", "--auth", "none", "--port", "8300"]
